Material 3
simple-login/Simple-Login-Android pull request #136
Opened 2024-11-05 21:03 UTC by StellarSand

In this PR:
- Use Material 3 components
- Initial support for Material You
- Updated gradle, dependencies, kotlin, java versions

> [!NOTE]
> - This is **not** a redesign.

Closes #132

2024-11-08 16:37 UTC, nguyenkims commented
Thanks for the MR! Our team will review it and come back to you!

2025-02-07 12:08 UTC, proton-pass requested changes

2025-02-07 12:08 UTC, proton-pass commented on SimpleLogin/app/src/main/java/io/simplelogin/android/module/share/ShareActivity.kt
> +        binding.prefixEditText.setSelection(binding.prefixEditText.text!!.count())
If prefixEditText is ever null this will cause a crash. Could you update it to avoid it?

2025-02-07 12:08 UTC, proton-pass commented on SimpleLogin/app/src/main/java/io/simplelogin/android/utils/extension/Context.kt
> +    return packageInfo.versionName!!
If versionName is ever null this will cause a crash. Could you update it to avoid it?

2025-02-07 16:33 UTC, StellarSand commented on SimpleLogin/app/src/main/java/io/simplelogin/android/module/share/ShareActivity.kt
> +        binding.prefixEditText.setSelection(binding.prefixEditText.text!!.count())
Sorry I have no idea why I made those changes in the first place. :smile:

2025-02-07 16:34 UTC, StellarSand commented on SimpleLogin/app/src/main/java/io/simplelogin/android/utils/extension/Context.kt
> +    return packageInfo.versionName!!
fixed now :)

2025-02-10 08:15 UTC, proton-pass commented on SimpleLogin/app/src/main/java/io/simplelogin/android/module/share/ShareActivity.kt
> +        binding.prefixEditText.setSelection(binding.prefixEditText.text!!.count())
Hey, you added it because otherwise, it would cause a compilation error. Right now, reverting it makes the code fail to compile. The ideal approach would be to write it in a more null-safe way. For example, you could add a .orEmpty().

2025-02-10 08:15 UTC, proton-pass commented on SimpleLogin/app/src/main/java/io/simplelogin/android/utils/extension/Context.kt
> +    return packageInfo.versionName!!
Same as above.

2025-05-06 19:06 UTC, StellarSand commented on SimpleLogin/app/src/main/java/io/simplelogin/android/utils/extension/Context.kt
> +    return packageInfo.versionName!!
Done.

2025-05-06 19:06 UTC, StellarSand commented on SimpleLogin/app/src/main/java/io/simplelogin/android/module/share/ShareActivity.kt
> +        binding.prefixEditText.setSelection(binding.prefixEditText.text!!.count())
Done.

2025-09-26 10:47 UTC, vinnyperella commented
Any update on this?

2026-05-05 02:51 UTC, ch2a commented
It's been a year, it would be nice to get this merged (the Android app needs some love 😃)
@nguyenkims @proton-pass

2026-05-05 09:06 UTC, steff2632 commented
yeah, the android app needs some serious love, I spent a couple hours on friday with a view to update it but if this PR from a year ago cant get approved maybe the project is dead and I should spend my time elsewhere

2026-05-05 10:18 UTC, ntnhon commented
Hey all, we've rewritten the app from scratch with Compose and Material 3. We'll publish the code shortly in order to receive contributions. Will keep you posted here.

2026-05-10 13:47 UTC, ntnhon commented
The v2 branch is now merged.

2026-05-10 13:47 UTC, closed without merging